language: java
bundler_args: --retry 1

addons:
  sonarcloud:
    organization: "dernasherbrezon-github"
    token:
      secure: "fVUuZApecVqcACFs9r9lcjAwvgRvYWx+0DiSQDDc+AKlc7i5E/c3u/qiDeSSC+y0SStEKe0Qv4Ur5HKqspzIURkMRb/opVXsAH+ZdfIVr3QayGD3FhOwlbaIVsBjXWtC3Sx401+9KB6bV7PoUTjOj9nhpyYBfiYiDk5+fSQZVi6CbVfPFM3hnss7M8t2wNnxuB4zx1ix/O17AOIjjOI07PtcpiMFIaJcXIys64y8W+lLuMRu8LVxtHZyLmv8XqXy/MZgBAt59hvlN1sQLQwd+/QOnFtclaQYxehjSTsNXGxAZEwvszHLXjYuYmZHCuDdV3JaBDHoteclinD6T1oGrAe7WTgB7wpv3FES8zBi4MtCF9SWIR1U0Tr0dyJEfba0jiRZ+XCaQYoG9W0GbOWtfA3TVufUab5bA0OtwpEs63s2XC6SH3S2Bp9uyw109Zt8tQhThc7K5Um0e73qXEVuJBLAoStDN+F0VCWOVOBNA9Ak8akO2mgdSY7Wt4gqDkktENKSrc4yrDYcB62skl8ELzsbRzTdG2UvPcwXYFvUXSy5SPHz/o83bJXuiW6tfXmTex/UqqJ4dftX5mbS47DS7/vlA5THHVI1D5Vvle9PgvEyEJ6aGGZAfvjlthYx5yADUo18jTGSl5QU+P1+B1OSYPSUjaUyfOUgF25bhdEk+3E="

cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sonar/cache

before_cache:
  - rm -rf $HOME/.m2/repository/com/aerse/

script:
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.scm.disabled=true -Dsonar.language=java
  - ./src/test/bash/bash_unit.sh ./src/test/bash/test_core.sh

